Fix associate jira with slack mention by email
pyconjp/jira-issue-report pull request #3
Opened 2017-05-05 09:04 UTC by Yu-taro

Associate JIRA user with Slack mention by email on report.
It has become necessary Slack API token by this fix.

* [ ] Load Use list from Slack API
    * [ ] Add Slack token to config.ini

2017-05-05 09:17 UTC, takanory requested changes
対応よろ。
TODOもissueにしといてほしい。もしくは、Slackにメッセージ投げるだけなんで、slack apiの方に書き換えちゃってもよいかと

2017-05-05 09:17 UTC, takanory commented on README.md
> +token = Slack API token
これ2つあるの冗長なんだよなー。API token設定するなら、投稿するところもそっちに統合したい感ある。
まぁ、TODOかな

2017-05-05 09:17 UTC, takanory commented on issue.py
> +def search_user_name_by_email(email, users):
重要: これは処理が無駄な感じなので、先にkeyがemail、valueがslack usernameっていう辞書を作りましょう

2017-05-05 09:17 UTC, takanory commented on issue.py
> +    json = response.json()
TODO: ここで辞書データを作りましょう。何回も引くことになるので

辞書内包表記で書けばこんな感じで行けるはず

```
>>> members = [{'email': 'takanori@pycon.jp', 'name': 'takanory'}, {'email': 'yutaro@pycon.jp', 'name': 'yutaro'}]
>>> {m['email']: m['name'] for m in members}
{'takanori@pycon.jp': 'takanory', 'yutaro@pycon.jp': 'yutaro'}
```

2017-05-06 05:29 UTC, takanory reviewed
このまんまでも大丈夫かと思います。

2017-05-06 05:29 UTC, takanory commented on issue.py
> +    payload = {'token': token}
アドバイス: あ、自分でrequestsで頑張ってたんですね。
Slacker使えば楽だったかも。まぁ、使わなくてもいいです。
https://github.com/os/slacker

2017-05-06 05:29 UTC, takanory commented on issue.py
> +    print(text)
このprintはいらなそう。

2017-05-06 05:29 UTC, takanory commented on issue.py
> +    url = SLACK_API + 'chat.postMessage'
アドバイス: こっちもSlacker使ったほうが楽そう

2017-05-06 05:29 UTC, takanory approved these changes

2017-05-06 05:29 UTC, takanory commented
@Yu-taro 実装はOKかと。Slacker使うかは判断よろ

2017-05-08 01:54 UTC, Yu-taro commented
@takanory これで行きましょう！

2017-05-09 02:00 UTC, merged